name: rl-test
channels:
  - pytorch-nightly
  - conda-forge
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - cudatoolkit=11.3
  - jupyterlab
  - numpy
  - pandas
  - matplotlib
  - atari_py #  - ale_py
  - swig # https://stackoverflow.com/questions/44198228/install-pybox2d-for-python-3-6-with-conda-4-3-21
  - box2d-py
  - tesseract # https://pythonforundergradengineers.com/how-to-install-pytesseract.html
  - pytesseract
  - pip # https://stackoverflow.com/questions/35245401/combining-conda-environment-yml-with-pip-requirements-txt
  - pip:
    - stable-baselines3[extra]
    - pyglet
    - highway-env
    - gym
    - pyglet
    # - gym[atari]
    # - gym-anytrading
    - protobuf==3.20.*
    - mss
    - pydirectinput
    # - pytesseract
    # - gym-retro # https://youtu.be/rzbFhu6So5U?t=245
    # - vizdoom # https://github.com/mwydmuch/ViZDoom
    - optuna # https://optuna.org/
    - snooty-lextudio # https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/283#issuecomment-792139136
    - joblib # https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-save-and-resume-studies
    - plotly # https://optuna.readthedocs.io/en/stable/reference/visualization/index.html#optuna-visualization
    - ipywidgets # https://github.com/plotly/plotly.py#jupyterlab-support
    - scikit-learn
